### ISSUE TITLE
Does this plugin work with gatsby.js for react?

### ISSUE THREAD

**Issue by didacta** [bryanbraun/checkboxland#12]
Unable to get it to run on first try importing the example code as it's own component 

Receiving the error 
`Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.` and 
`TypeError: Cannot set property 'innerHTML' of null`

thank you!

**Comment by bryanbraun** [comment]
Checkboxland manipulates the DOM so you'll may need to be careful in how you integrate it with React. Try these suggestions (if you haven't already) and see if it helps: https://reactjs.org/docs/integrating-with-other-libraries.html#integrating-with-dom-manipulation-plugins

**Comment by bryanbraun** [comment]
Closing this now... let me know if anything else is needed here. 👍
