### ISSUE TITLE
Normalize checkbox colors across browsers using "accent-color"

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/checkboxland#19]
Currently different browsers display different default checkbox colors:

Edge: ![image](https://user-images.githubusercontent.com/1256329/137068627-04202a47-4e4c-42a1-babd-51d0d85eabf2.png)

Safari: ![image](https://user-images.githubusercontent.com/1256329/137068720-7c6fb03b-5acc-4fe6-92ea-fc839abcc792.png)

Chrome: ![image](https://user-images.githubusercontent.com/1256329/137068679-fa5c4a6a-bbb4-4e73-b784-40f14914a1bd.png)

We can use [the new accent-color CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color) to make them all the same color across browsers (at least for the browsers that support it). I'd suggest that we make them all the same as the safari color (since it's blue-ish and that browser doesn't yet support accent-color yet).

For now, we can start by just adding these style changes to this normalize stylesheet (and possibly renaming the stylesheet from `normalize-size.css` to `normalize.css`): https://github.com/bryanbraun/checkboxland/blob/main/docs/css/cbl-normalize-size.css .

**Comment by umair-fayaz** [comment]
Hi, I would like to work on it
