### ISSUE TITLE
Add a basic "Dithering" option to renderImage() and renderVideo()

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/checkboxland#20]
Rendering Images and Videos would likely look better if we were to pass the pixel data through a dithering algorithm (see https://en.wikipedia.org/wiki/Dither).

We could probably pull in a library or basic algorithm off the shelf, add it to [renderMediaAsCheckboxes.js](https://github.com/bryanbraun/checkboxland/blob/main/src/plugins/media/renderMediaAsCheckboxes.js), and expose it as an option in the `renderImage()` and `renderVideo()` plugins (either as a boolean, or—if there are multiple options—as a string/enum).

**Comment by bryanbraun** [comment]
Hey @karelbilek, thanks for including the videos demonstrating the approaches. You're right... the sharpened one looks much better. 🎉 

I'm still working through my inbox but I wanted to let you know that I saw this and should be able to review the PR sometime in the next couple of days.

**Comment by bryanbraun** [comment]
Ok @karelbilek, I've been taking a closer look at this today. I really like the results you were able to get with this library. I think there's a few adjustments I want to make... mostly to the API and how to pull in the dithering algorithms from that library.

I'm gonna make a few changes on top of your changes and if it's working well, we'll get it merged. 😄

**Comment by karelbilek** [comment]
The original library is not that complex either, we (well... you, sorry :) ) can just copy the algorithm over here to better fit the rest of the code

**Comment by bryanbraun** [comment]
@karelbilek, thanks! I did what you said, merged your PR, and did a follow-up commit where i copied over the algorithms and  made a few other changes to preserve backwards-compatibility. You can see a demo here: https://www.bryanbraun.com/checkboxland/docs/demos/webcam-test/

Thanks for all the help with this. 🏆
