### ISSUE TITLE
User input events

### ISSUE THREAD

**Issue by KonradLinkowski** [bryanbraun/checkboxland#8]
Is there any way to detect user clicks? Do you plan to add this in the future?

**Comment by bryanbraun** [comment]
Hey @KonradLinkowski, great question.

As soon as the Checkbox grid is created, you can add your own event listeners to the markup. The markup doesn't change once the grid is created, so the events won't get altered or removed.

As an example, the "logo" in the top left corner of [the docs page](https://www.bryanbraun.com/checkboxland/) is clickable. [Here's the code that adds the event listener](https://github.com/bryanbraun/checkboxland/blob/master/docs/js/logo.js#L12-L15).

I feel like this works well enough that I'm not planning on adding anything else for events. But let me know if you run into a use-case where a plain `addEventListener` won't work.

**Comment by KonradLinkowski** [comment]
This works fine for full grid clicking, but it detecting which checkbox was clicked isn't so simple (perhaps I'm wrong).
I was thinking more of an event which carry an information about position of clicked checkbox and it's state.

**Comment by bryanbraun** [comment]
Ahhh, I see. I totally get how that could be useful.

This would make a good [plugin](https://www.bryanbraun.com/checkboxland/#using-plugins). Many of the example features (like `marquee`, and `print`) are plugins that I've included in the main library.

My current thinking is that new features like this should be built as an external plugin first, and then, if it proves useful, I'd consider pulling it into the main library (this [is described here in the README](https://github.com/bryanbraun/checkboxland#contributing)).

If you have the time or interest to take a pass at this, I'll link to your plugin from this issue and [here in the docs](https://www.bryanbraun.com/checkboxland/#existing-plugins). It wouldn't even need to be packaged on NPM or even in a repo... I'd be cool with linking to a gist too, as long as it was functional).

**Comment by bryanbraun** [comment]
Thanks for the help @KonradLinkowski. The feature is now merged and published in [version 1.2.0](https://github.com/bryanbraun/checkboxland/releases/tag/v1.2.0). 👍
